/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DataRouteImport } from './routes/data'
import { Route as MapRouteImport } from './routes/map'
import { Route as ApiPublicEra5DailyRouteImport } from './routes/api/public/era5/daily'
import { Route as ApiPublicEra5SummaryRouteImport } from './routes/api/public/era5/summary'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DataRoute = DataRouteImport.update({
  id: '/data',
  path: '/data',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicEra5DailyRoute = ApiPublicEra5DailyRouteImport.update({
  id: '/api/public/era5/daily',
  path: '/api/public/era5/daily',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicEra5SummaryRoute = ApiPublicEra5SummaryRouteImport.update({
  id: '/api/public/era5/summary',
  path: '/api/public/era5/summary',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/data': typeof DataRoute
  '/map': typeof MapRoute
  '/api/public/era5/daily': typeof ApiPublicEra5DailyRoute
  '/api/public/era5/summary': typeof ApiPublicEra5SummaryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/data': typeof DataRoute
  '/map': typeof MapRoute
  '/api/public/era5/daily': typeof ApiPublicEra5DailyRoute
  '/api/public/era5/summary': typeof ApiPublicEra5SummaryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/data': typeof DataRoute
  '/map': typeof MapRoute
  '/api/public/era5/daily': typeof ApiPublicEra5DailyRoute
  '/api/public/era5/summary': typeof ApiPublicEra5SummaryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/data'
    | '/map'
    | '/api/public/era5/daily'
    | '/api/public/era5/summary'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/data'
    | '/map'
    | '/api/public/era5/daily'
    | '/api/public/era5/summary'
  id:
    | '__root__'
    | '/'
    | '/data'
    | '/map'
    | '/api/public/era5/daily'
    | '/api/public/era5/summary'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DataRoute: typeof DataRoute
  MapRoute: typeof MapRoute
  ApiPublicEra5DailyRoute: typeof ApiPublicEra5DailyRoute
  ApiPublicEra5SummaryRoute: typeof ApiPublicEra5SummaryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data': {
      id: '/data'
      path: '/data'
      fullPath: '/data'
      preLoaderRoute: typeof DataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/era5/daily': {
      id: '/api/public/era5/daily'
      path: '/api/public/era5/daily'
      fullPath: '/api/public/era5/daily'
      preLoaderRoute: typeof ApiPublicEra5DailyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/era5/summary': {
      id: '/api/public/era5/summary'
      path: '/api/public/era5/summary'
      fullPath: '/api/public/era5/summary'
      preLoaderRoute: typeof ApiPublicEra5SummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DataRoute: DataRoute,
  MapRoute: MapRoute,
  ApiPublicEra5DailyRoute: ApiPublicEra5DailyRoute,
  ApiPublicEra5SummaryRoute: ApiPublicEra5SummaryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
